import sqlite3
from pathlib import Path
import sys

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'scripts'))
from migrate_sqlite_to_postgres import TABLE_ORDER, IDENTITY_TABLES, migrate_table
from verify_integrity import CHECKS


def database():
    # Execute the portable SQL clauses; only identity syntax differs on SQLite.
    db = sqlite3.connect(':memory:')
    db.row_factory = sqlite3.Row
    db.executescript('''PRAGMA foreign_keys=ON;
        CREATE TABLE users(id INTEGER PRIMARY KEY);
        CREATE TABLE lineups(id INTEGER PRIMARY KEY, user_id INTEGER, status TEXT);
        INSERT INTO users VALUES (1);
        INSERT INTO lineups VALUES (1,1,'banned');''')
    sql = Path('migrations/0016_lineup_moderation.sql').read_text(encoding='utf-8')
    sql = sql.replace('BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'INTEGER PRIMARY KEY AUTOINCREMENT').replace('BIGINT', 'INTEGER')
    db.executescript(sql)
    db.execute("INSERT INTO lineup_moderation(lineup_id,state,reason,prior_status,created_at,updated_at) VALUES(1,'banned','reason','normal','now','now')")
    db.commit()
    return db


def test_migration_executes_and_enforces_state_proposal_and_ownership():
    db = database()
    for sql in ["UPDATE lineup_moderation SET state='anything'", "UPDATE lineup_moderation SET notice_state='anything'", "UPDATE lineup_moderation SET notice_state='archived'", "UPDATE lineup_moderation SET prior_status='banned'", "UPDATE lineup_moderation SET state='pending'", "UPDATE lineup_moderation SET lineup_id=99"]:
        with pytest.raises(sqlite3.IntegrityError):
            db.execute(sql)
        db.rollback()
    db.execute("UPDATE lineup_moderation SET state='pending',proposed_name='changed',proposed_code='#CODE',proposed_season_id='s18'")
    assert db.execute('SELECT state FROM lineup_moderation').fetchone()['state'] == 'pending'
    db.close()


def test_integrity_checks_detect_restriction_mismatch():
    db = database()
    sql = dict(CHECKS)['moderation restriction matches lineup status']
    assert db.execute(sql).fetchone()[0] == 0
    db.execute("UPDATE lineups SET status='normal'")
    assert db.execute(sql).fetchone()[0] == 1
    db.close()


def test_import_preserves_moderation_and_event_history_in_dependency_order():
    assert TABLE_ORDER.index('users') < TABLE_ORDER.index('lineups') < TABLE_ORDER.index('lineup_moderation') < TABLE_ORDER.index('lineup_moderation_events')
    assert 'lineup_moderation_events' in IDENTITY_TABLES
    assert 'lineup_moderation' not in IDENTITY_TABLES
    db = database()
    class Cursor:
        rows = []
        def executemany(self, sql, params):
            self.sql = sql
            self.rows = params
    cursor = Cursor()
    assert migrate_table(db, cursor, 'lineup_moderation') == 1
    assert '"proposed_code"' in cursor.sql and '"notice_state"' in cursor.sql
    assert cursor.rows[0][0] == 1
    db.close()
