CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    applied_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    nickname TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    last_login_at TEXT
);

CREATE TABLE IF NOT EXISTS lineups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    name TEXT NOT NULL,
    code TEXT NOT NULL,
    season_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'normal',
    admin_like_adjustment INTEGER NOT NULL DEFAULT 0,
    admin_copy_adjustment INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    lineup_id BIGINT NOT NULL REFERENCES lineups(id),
    like_date TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE(user_id, lineup_id, like_date)
);

CREATE TABLE IF NOT EXISTS copy_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lineup_id BIGINT NOT NULL REFERENCES lineups(id),
    user_id BIGINT REFERENCES users(id),
    ip_address TEXT,
    copy_key TEXT NOT NULL,
    bucket_start TEXT NOT NULL,
    counted INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    UNIQUE(lineup_id, copy_key, bucket_start)
);

CREATE TABLE IF NOT EXISTS copy_action_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    season_id TEXT,
    lineup_id BIGINT REFERENCES lineups(id),
    live_comp_id TEXT,
    user_id BIGINT REFERENCES users(id),
    visitor_token TEXT,
    ip_address TEXT,
    source_page TEXT NOT NULL DEFAULT '',
    success INTEGER NOT NULL DEFAULT 1,
    counted INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS live_comp_global_stats (
    stats_key TEXT PRIMARY KEY,
    total_copy_count INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS live_comp_global_daily_stats (
    copy_date TEXT PRIMARY KEY,
    copy_count INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS cache_state (
    cache_key TEXT PRIMARY KEY,
    revision INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app_settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    lineup_id BIGINT NOT NULL REFERENCES lineups(id),
    created_at TEXT NOT NULL,
    UNIQUE(user_id, lineup_id)
);

CREATE TABLE IF NOT EXISTS reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id BIGINT NOT NULL REFERENCES users(id),
    lineup_id BIGINT NOT NULL REFERENCES lineups(id),
    reason TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TEXT NOT NULL,
    handled_at TEXT,
    handled_by BIGINT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS recent_lineup_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    lineup_id BIGINT NOT NULL REFERENCES lineups(id),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(user_id, lineup_id)
);

CREATE TABLE IF NOT EXISTS recent_lineup_copies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    lineup_id BIGINT NOT NULL REFERENCES lineups(id),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(user_id, lineup_id)
);

CREATE TABLE IF NOT EXISTS login_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    ip_address TEXT NOT NULL,
    success INTEGER NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS visit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_date TEXT NOT NULL,
    visitor_key TEXT NOT NULL,
    visitor_kind TEXT NOT NULL,
    user_id BIGINT REFERENCES users(id),
    visitor_token TEXT,
    ip_address TEXT,
    page_key TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE(visit_date, page_key, visitor_key)
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT REFERENCES users(id),
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id BIGINT,
    before_json TEXT,
    after_json TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS rate_limits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope TEXT NOT NULL,
    key TEXT NOT NULL,
    window_start TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    UNIQUE(scope, key, window_start)
);

CREATE TABLE IF NOT EXISTS growth_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name TEXT NOT NULL,
    user_id BIGINT REFERENCES users(id),
    visitor_token TEXT,
    ip_address TEXT,
    ref_lineup_id BIGINT REFERENCES lineups(id),
    page_key TEXT,
    payload_json TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS guestbook_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    nickname TEXT NOT NULL,
    content TEXT NOT NULL,
    ip_address TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS patch_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    version TEXT NOT NULL DEFAULT '',
    source_url TEXT NOT NULL DEFAULT '',
    summary_markdown TEXT NOT NULL,
    original_text TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'draft',
    published_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_growth_events_name_created_at
ON growth_events (event_name, created_at);

CREATE INDEX IF NOT EXISTS idx_growth_events_user_created_at
ON growth_events (user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_growth_events_visitor_created_at
ON growth_events (visitor_token, created_at);

CREATE INDEX IF NOT EXISTS idx_likes_lineup_created_at
ON likes (lineup_id, created_at);

CREATE INDEX IF NOT EXISTS idx_copy_events_lineup_created_at
ON copy_events (lineup_id, created_at);

CREATE INDEX IF NOT EXISTS idx_copy_action_events_target_created_at
ON copy_action_events (target_type, target_id, created_at);

CREATE INDEX IF NOT EXISTS idx_copy_action_events_user_created_at
ON copy_action_events (user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_lineups_user_status_updated_at
ON lineups (user_id, status, updated_at);

CREATE INDEX IF NOT EXISTS idx_lineups_season_status_updated_at
ON lineups (season_id, status, updated_at);

CREATE INDEX IF NOT EXISTS idx_lineups_status_updated_id
ON lineups (status, updated_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_likes_created_lineup
ON likes (created_at, lineup_id);

CREATE INDEX IF NOT EXISTS idx_copy_events_counted_created_lineup
ON copy_events (counted, created_at, lineup_id);

CREATE INDEX IF NOT EXISTS idx_patch_notes_status_published_at
ON patch_notes (status, published_at DESC, id DESC);

CREATE OR REPLACE FUNCTION jcc_touch_cache_state()
RETURNS trigger AS $$
BEGIN
    UPDATE cache_state
    SET revision = revision + 1,
        updated_at = to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
    WHERE cache_key = ANY(TG_ARGV);
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_lineups_cache_state_insert ON lineups;
CREATE TRIGGER trg_lineups_cache_state_insert
AFTER INSERT ON lineups
FOR EACH ROW EXECUTE FUNCTION jcc_touch_cache_state('home', 'score');

DROP TRIGGER IF EXISTS trg_lineups_cache_state_update ON lineups;
CREATE TRIGGER trg_lineups_cache_state_update
AFTER UPDATE ON lineups
FOR EACH ROW EXECUTE FUNCTION jcc_touch_cache_state('home', 'score');

DROP TRIGGER IF EXISTS trg_lineups_cache_state_delete ON lineups;
CREATE TRIGGER trg_lineups_cache_state_delete
AFTER DELETE ON lineups
FOR EACH ROW EXECUTE FUNCTION jcc_touch_cache_state('home', 'score');

DROP TRIGGER IF EXISTS trg_likes_cache_state_insert ON likes;
CREATE TRIGGER trg_likes_cache_state_insert
AFTER INSERT ON likes
FOR EACH ROW EXECUTE FUNCTION jcc_touch_cache_state('home', 'score');

DROP TRIGGER IF EXISTS trg_likes_cache_state_update ON likes;
CREATE TRIGGER trg_likes_cache_state_update
AFTER UPDATE ON likes
FOR EACH ROW EXECUTE FUNCTION jcc_touch_cache_state('home', 'score');

DROP TRIGGER IF EXISTS trg_likes_cache_state_delete ON likes;
CREATE TRIGGER trg_likes_cache_state_delete
AFTER DELETE ON likes
FOR EACH ROW EXECUTE FUNCTION jcc_touch_cache_state('home', 'score');

DROP TRIGGER IF EXISTS trg_copy_events_cache_state_insert ON copy_events;
CREATE TRIGGER trg_copy_events_cache_state_insert
AFTER INSERT ON copy_events
FOR EACH ROW EXECUTE FUNCTION jcc_touch_cache_state('home', 'score');

DROP TRIGGER IF EXISTS trg_copy_events_cache_state_update ON copy_events;
CREATE TRIGGER trg_copy_events_cache_state_update
AFTER UPDATE ON copy_events
FOR EACH ROW EXECUTE FUNCTION jcc_touch_cache_state('home', 'score');

DROP TRIGGER IF EXISTS trg_copy_events_cache_state_delete ON copy_events;
CREATE TRIGGER trg_copy_events_cache_state_delete
AFTER DELETE ON copy_events
FOR EACH ROW EXECUTE FUNCTION jcc_touch_cache_state('home', 'score');

DROP TRIGGER IF EXISTS trg_favorites_cache_state_insert ON favorites;
CREATE TRIGGER trg_favorites_cache_state_insert
AFTER INSERT ON favorites
FOR EACH ROW EXECUTE FUNCTION jcc_touch_cache_state('home');

DROP TRIGGER IF EXISTS trg_favorites_cache_state_update ON favorites;
CREATE TRIGGER trg_favorites_cache_state_update
AFTER UPDATE ON favorites
FOR EACH ROW EXECUTE FUNCTION jcc_touch_cache_state('home');

DROP TRIGGER IF EXISTS trg_favorites_cache_state_delete ON favorites;
CREATE TRIGGER trg_favorites_cache_state_delete
AFTER DELETE ON favorites
FOR EACH ROW EXECUTE FUNCTION jcc_touch_cache_state('home');

