CREATE TABLE IF NOT EXISTS site_notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    link_url TEXT NOT NULL DEFAULT '',
    link_text TEXT NOT NULL DEFAULT '',
    is_active INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_site_notices_single_active
ON site_notices (is_active)
WHERE is_active = 1;

INSERT INTO site_notices (title, message, link_url, link_text, is_active, created_at, updated_at)
SELECT
    notice_payload.title,
    notice_payload.message,
    COALESCE(notice_payload.link_url, ''),
    COALESCE(notice_payload.link_text, ''),
    CASE WHEN notice_enabled.setting_value = 'true' THEN 1 ELSE 0 END,
    to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
FROM app_settings AS notice_data
LEFT JOIN app_settings AS notice_enabled
    ON notice_enabled.setting_key = 'notice_enabled'
CROSS JOIN LATERAL jsonb_to_record(notice_data.setting_value::jsonb) AS notice_payload(
    title TEXT,
    message TEXT,
    link_url TEXT,
    link_text TEXT
)
WHERE notice_data.setting_key = 'notice_data'
  AND notice_data.setting_value <> '{}'
  AND COALESCE(notice_payload.title, '') <> ''
  AND COALESCE(notice_payload.message, '') <> ''
  AND NOT EXISTS (SELECT 1 FROM site_notices);
