ALTER TABLE site_notices ADD COLUMN IF NOT EXISTS jump_season_id TEXT NOT NULL DEFAULT '';
ALTER TABLE site_notices ADD COLUMN IF NOT EXISTS jump_tab TEXT NOT NULL DEFAULT '';
ALTER TABLE site_notices ADD COLUMN IF NOT EXISTS marquee_enabled INTEGER NOT NULL DEFAULT 1;
