CREATE TABLE IF NOT EXISTS live_comp_copy_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id TEXT NOT NULL,
    live_comp_id TEXT NOT NULL,
    user_id BIGINT REFERENCES users(id),
    ip_address TEXT,
    copy_key TEXT NOT NULL,
    bucket_start TEXT NOT NULL,
    counted INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    UNIQUE(season_id, live_comp_id, copy_key, bucket_start)
);

CREATE INDEX IF NOT EXISTS idx_live_comp_copy_events_target_created_at
ON live_comp_copy_events (season_id, live_comp_id, created_at);
