-- Historic device information cannot be reconstructed. Keep old rows unknown.
ALTER TABLE visit_events ADD COLUMN IF NOT EXISTS device_type TEXT NOT NULL DEFAULT 'unknown'
    CHECK (device_type IN ('mobile','tablet','desktop','unknown'));
ALTER TABLE copy_action_events ADD COLUMN IF NOT EXISTS device_type TEXT NOT NULL DEFAULT 'unknown'
    CHECK (device_type IN ('mobile','tablet','desktop','unknown'));
CREATE TABLE IF NOT EXISTS search_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL,
    visitor_key TEXT NOT NULL,
    user_id INTEGER REFERENCES users(id),
    query TEXT NOT NULL,
    season_id TEXT NOT NULL,
    sort_key TEXT NOT NULL,
    result_count INTEGER NOT NULL CHECK (result_count >= 0),
    device_type TEXT NOT NULL DEFAULT 'unknown' CHECK (device_type IN ('mobile','tablet','desktop','unknown')),
    created_at TEXT NOT NULL,
    UNIQUE(visitor_key, event_id)
);
CREATE INDEX IF NOT EXISTS idx_search_events_created_at ON search_events(created_at);
CREATE INDEX IF NOT EXISTS idx_visit_events_created_at ON visit_events(created_at);
